### PR TITLE
Add CAS overlay for issue#2151

### PR DESCRIPTION
**Pull request by randomuser878**

### CODE REVIEW

**Comment by mmoayyed** [comment]
Could you also share your settings that deal with the ticket registr? redact as you see fit.

**Comment by randomuser878** [comment]
I believe they are in the cas.properties as part of this pull but here they are as well.  Db/user/pwd are not the real values. 

ticketreg.database.ddl.auto=create-drop
ticketreg.database.dialect=org.hibernate.dialect.MySQLInnoDBDialect
ticketreg.database.batchSize=10
ticketreg.database.driverClass=com.mysql.jdbc.Driver
ticketreg.database.url=jdbc:mysql://127.0.0.1:3306/cas4v2
ticketreg.database.user=cas
ticketreg.database.password=cas
ticketreg.database.pool.minSize=6
ticketreg.database.pool.maxSize=18
ticketreg.database.pool.maxWait=10000
ticketreg.database.pool.maxIdleTime=120
ticketreg.database.pool.acquireIncrement=6
ticketreg.database.pool.idleConnectionTestPeriod=30
ticketreg.database.pool.acquireRetryAttempts=5
ticketreg.database.pool.acquireRetryDelay=2000
ticketreg.database.pool.connectionHealthQuery=select 1

accept.authn.users=casuser::Mellon

# Default Expiration Policy, short to replicate issue quickly.
tgt.maxTimeToLiveInSeconds=300
tgt.timeToKillInSeconds=150

deployerConfigContext.xml has only one change from vanilla.
    
    <alias name="jpaTicketRegistry" alias="ticketRegistry" />

Thanks.

**Comment by mmoayyed** [comment]
Ah you're right. Sorry, missed those!

**Comment by mmoayyed** [comment]
Have you tried using the MySQLDialect or upgrading the MySql driver version ?

**Pull request merged**
