### PR TITLE
Can't get Hazelcast TicketRegistry to work

### PR DESCRIPTION
**Pull request by stephanarts**
For some reason the ticketregistry won't be enabled... not sure what I'm doing wrong here.

### CODE REVIEW

**Comment by mmoayyed** [comment]
You may want to try with RC3-SNAPSHOT, but even with RC2, I can see HZ is correctly initialized and activated.

**Comment by mmoayyed** [comment]
Essentially, not sure what you have in mind by "won't be enabled". What is your definition of "enabled" ?

**Comment by mmoayyed** [comment]
Proof from the logs:

```
016-09-30 15:08:06,922 WARN [com.hazelcast.config.MapConfig] - <As of version 3.7, `minEvictionCheckMillis` and `evictionPercentage` are deprecated due to the eviction mechanism change. New eviction mechanism uses a probabilistic algorithm based on sampling. Please see documentation for further details>
2016-09-30 15:08:06,954 INFO [org.apereo.cas.configuration.support.Beans] - <Ticket registry encryption/signing is turned off. This MAY NOT be safe in a clustered production environment. Consider using other choices to handle encryption, signing and verification of ticket registry tickets.>
2016-09-30 15:08:06,971 INFO [org.apereo.cas.ticket.registry.HazelcastTicketRegistry] - <Setting up Hazelcast Ticket Registry instance HazelcastInstance{name='localhost', node=[localhost]:5701} with name tickets>
```

**Comment by stephanarts** [comment]
Something must be wrong with my environment then... I don't see those entries in my logs.

**Comment by mmoayyed** [comment]
What do you see in the logs?

**Comment by stephanarts** [comment]
That there is something is wrong with my eclipse environment... I keep deploying the same CAS 5.0-RC2-SNAPSHOT version for some reason. - Not everything is 'old', I do get the new log4j stuff when I change the configuration. It appears it is not using the new pom.xml file when I change it.

**Comment by stephanarts** [comment]
It is working:

> java.lang.IllegalStateException: Could not evaluate condition on org.springframework.cloud.config.server.config.EnvironmentRepositoryConfiguration due to org/apache/ignite/spi/discovery/tcp/ipfinder/TcpDiscoveryIpFinder not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)

Okay, I am getting errors... but that's something I can fix. Basically, eclipse is doing nasty things caching maven configurations and java classes... :-p

My punishment for trying to use such newfangled tools like an IDE...

**Comment by dima767** [comment]
You should definitely give https://www.jetbrains.com/idea/ a good try ;-) (Disclaimer: this is NOT a paid advertisement for Jetbrains)

Cheers,
D.

**Comment by stephanarts** [comment]
Not using eclipse solved everything

Op 30 sep. 2016 3:15 p.m. schreef "Dmitriy Kopylenko" <
notifications@github.com>:

You should definitely give https://www.jetbrains.com/idea/ a good try ;-)
(Disclaimer: this is NOT a paid advertisement for Jetbrains)

Cheers,
D.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/cas-projects/cas-issues/pull/17#issuecomment-250741401>,
or mute the thread

**Pull request merged**
